version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: elelden_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elelden_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - elelden_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elelden_backend
    restart: unless-stopped
    environment:
      ENV: production
      SERVER_PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: appuser
      DB_PASSWORD: apppassword
      DB_DATABASE: elelden_db
      JWT_SECRET: your-production-jwt-secret
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - elelden_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elelden_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - elelden_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: elelden_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - elelden_network

volumes:
  mysql_data:
  redis_data:

networks:
  elelden_network:
    driver: bridge
